version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: cryptoapp
      MYSQL_TCP_PORT: 3306
    ports:
      - 3399:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  mongo:
    image: mongo:latest
    environment: 
      MONGO_INITDB_DATABASE: cryptoapp
    ports:
      - 27019:27017
  io:
    environment:
      NODE_ENV: staging
    build:
      context: .
      dockerfile: ./Dockerfile.io
    ports:
      - 8186:3000
  worker:
    environment:
      NODE_ENV: staging
    build:
      context: .
      dockerfile: ./Dockerfile.worker
  app:
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: staging
      GITHUB_CLIENT_SECRET: 7cd0a07e7784d2714a541093c263e49cf0bc70d0
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - 8082:3000
